# This configuration file is for the **development** setup.
# For a production example please refer to setup/docker-compose.yml.
version: '3'
services:
  redis:
    image: redis:3-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  postgres:
    image: postgres:9.5-alpine
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    ports:
      - "5432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
