"""add folder api - use correct message

Revision ID: 245a77dd4aea
Revises: ae4c5a8f0f14
Create Date: 2020-07-21 13:45:21.735000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245a77dd4aea'
down_revision = 'ae4c5a8f0f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('catalog', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folder_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('view_only', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('view_only', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'dashboards', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dashboards', 'folder_structures', ['folder_id'], ['id'])
    op.add_column(u'data_sources', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data_sources', 'folder_structures', ['folder_id'], ['id'])
    op.add_column(u'queries', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'queries', 'folder_structures', ['folder_id'], ['id'])
    op.add_column(u'users', sa.Column('is_super', sa.Boolean(), nullable=False))
    op.add_column(u'visualizations', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'visualizations', 'folder_structures', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visualizations', type_='foreignkey')
    op.drop_column(u'visualizations', 'folder_id')
    op.drop_column(u'users', 'is_super')
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column(u'queries', 'folder_id')
    op.drop_constraint(None, 'data_sources', type_='foreignkey')
    op.drop_column(u'data_sources', 'folder_id')
    op.drop_constraint(None, 'dashboards', type_='foreignkey')
    op.drop_column(u'dashboards', 'folder_id')
    op.drop_table('query_groups')
    op.drop_table('dashboard_groups')
    op.drop_table('folder_structures')
    # ### end Alembic commands ###
