"""Add archive field to visualization

Revision ID: 54d751c9fabe
Revises: 7222bbcd94c4
Create Date: 2019-11-13 21:45:06.313055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d751c9fabe'
down_revision = '7222bbcd94c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visualizations', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.execute('UPDATE visualizations SET is_archived=false')
    op.alter_column('visualizations', 'is_archived', nullable=False)
    op.create_index(op.f('ix_visualizations_is_archived'), 'visualizations', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visualizations_is_archived'), table_name='visualizations')
    op.drop_column('visualizations', 'is_archived')
    # ### end Alembic commands ###
