"""Add field to dashboard

Revision ID: a43f6207de38
Revises: fe8b8cd7c661
Create Date: 2019-12-04 21:54:07.183179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43f6207de38'
down_revision = 'fe8b8cd7c661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('background_image', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'background_image')
    # ### end Alembic commands ###
