"""Add two fields for dashboard

Revision ID: ae4c5a8f0f14
Revises: a43f6207de38
Create Date: 2019-12-15 23:12:16.495875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4c5a8f0f14'
down_revision = 'a43f6207de38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('description', sa.String(length=4096), nullable=True))
    op.add_column('dashboards', sa.Column('type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'type')
    op.drop_column('dashboards', 'description')
    # ### end Alembic commands ###
